[project]
name = "myapp"
version = "0.1.0"
authors = [
  { name="Hari Karthick", email="hari.ksp@zohointern.com" },
]
description = "A simple chat app to explore streamlit and software engineering basics"
dependencies = [
  "streamlit", 
  "supabase", 
  "python-dotenv", 
  "psycopg2-binary"
]